proxy:
  listen:
    address: "127.0.0.0.1"
    port: 8080
  services:
    - name: my-service
      domain: my-service.my-company.com
      hosts:
        - address: 127.0.0.1
          port: 8888
          retryPolicy:
            - timeout: 5
              retries: 5
        - address: 127.0.0.1
          port: 9999
          retryPolicy:
            - timeout: 5
              retries: 5
      lbPolicy: ROUND_
      tcpHealthcheck:
        - interval: 15.0
          timeout: 5.0

