proxy:
  listen:
    address: "127.0.0.1"
    port: 8080
  services:
    - name: my-service
      domain: my-service.my-company.com
      hosts:
        - address: 172.19.0.2
          port: 9090
          retryPolicy:
            - timeout: 2
              retries: 3
        - address: 172.19.0.3
          port: 9090
          retryPolicy:
            - timeout: 2
              retries: 3
        - address: 192.168.10.1
          port: 9090
          retryPolicy:
            - timeout: 2
              retries: 3
      lbPolicy: ROUND_ROBIN
      tcpHealthcheck:
        - interval: 15
          timeout: 1.0

